apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  # This is equal to docker. docker run -d --name nginx nginx
  - name: nginx
    image: nginx  
  nodeSelector:
    hardware: gpu  
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"  